# ワークフローの名前（GitHubのActionsタブで表示される）
name: .NET Build and Test

# いつこのワークフローを実行するかを定義
on:
  push:                            # コードをpushしたとき
    branches: [ "master" ]  # masterブランチに対してのみ実行
  pull_request:                 # プルリクエストを作成/更新したとき
    branches: [ "master" ]  # masterブランチ宛ての場合に実行

# 実行するジョブの一覧
jobs:
  build:                            # ジョブのID（任意の名前でOK）
    runs-on: ubuntu-latest  # 実行環境（Linuxの最新版で実行）
    steps:                         # ジョブの中で行う処理のステップ

    # リポジトリのソースコードをチェックアウトする
    - uses: actions/checkout@v4
 
    # .NET 8 をインストールして利用可能にする
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

     # NuGetパッケージの依存関係を復元する
    - name: Restore dependencies  
      run: dotnet restore
      
      # プロジェクトをビルド（--no-restoreでrestoreを省略）
    - name: Build
      run: dotnet build --no-restore
      
      # 単体テストを実行（事前にビルド済みなので--no-build）
    - name: Test
      run: dotnet test --no-build --verbosity normal